TYPO3:
  Neos:
    GoogleAnalytics:
      authentication:
        # Application name for the consent screen
        applicationName: 'TYPO3 Neos'
        # "Client ID" of the OAuth 2.0 "Client ID for web application"
        clientId: '328117705510-p0va3f0v1fdn2r5gkis5kr5jaaa7gb86.apps.googleusercontent.com'
        # "Client Secret" of the OAuth 2.0 "Client ID for web application"
        clientSecret: "-----BEGIN PRIVATE KEY-----\nMIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANApgZsYt87sI0xH\n/klr7QOHOWBZAwNbF4QzuEHj5bASVvOPmD4pXWmCI1K/9W0H9/CnkOi5VycOuB5C\nO2QGBovX/R0sa1YZODcXhBfxL+XNOf5/zJX1VCw4fK+1biaKC1hWsv4Y8hVg/Dy0\nuqtfGqLQSaZ1ppup8XQhdywI2wgtAgMBAAECgYEAyS/kiO9Z748BCp/mYDYEbE2M\noddF9z9aOjb2lhBalVMUYPDfFu1J0EisNTU8UnXKJ/j8MEG5vxEV2IDw/9pnBZGv\nJAf5BngQaMX9rvHGGepqTAFXn0CQtBHIAHIjH00Tq9mv1zYyjwFX6WKiAONjl9/V\n7gD5+mozoQeRfXM0Ko0CQQDn+aCxfeC49xDD0pQSz7yrdZhAkW4Y5e4ZHo0fw7aO\nWlraTStk97jEtNYrFmdVLs6gf5XLhaO81+I/Rr+cbJW3AkEA5biGBJfGQq+/yyZN\nSfBjEgc86jN2TMu7E0E0TGjAVnhgIdrLwV5oN+fco7qNnWK9fsy2h2EI2gsh3H0G\nMjexOwJBAJ8pcY4WlieSrRgO1bYKfqMN7kbvAaFnsXPeuGmA+TK23/tEU2/VYBrn\nEMNDfea+VNtebsLTkMKzRPKxciq7fgUCQEKRQQytqn8CjLJiq/zkEuFThZxcQ0in\ntNM0juIhbLLh+QF2dJrZL5wbrT0ovwa/aSgITFBYlwcQOMS62gPNTacCQFxFZ/PQ\nnLTsdrr9R5Jg6tIqMauefO89G4hplqe8TbxASZ3G7WBet+gDzemUjNTwiu4kyBnz\n//wG3A81kLJRksI\u003d\n-----END PRIVATE KEY-----\n"
        # "API Key" of the Public API access credential "Key for server applications"
        developerKey: 'AIzaSyDWeZMDkr6hBtiiUA6vucQc2B5g3FSExJ8'
      stats:
        uniquePageviewsPerDay:
          metrics: 'ga:uniquePageviews'
          dimensions: 'ga:date'
        basic:
          metrics: 'ga:pageviews,ga:uniquePageviews,ga:users'
        uniquePageviewsByUserType:
          metrics: 'ga:uniquePageviews'
          dimensions: 'ga:userType'
        uniquePageviewsByDeviceCategory:
          metrics: 'ga:uniquePageviews'
          dimensions: 'ga:deviceCategory'
      sites:
        sfi:
          trackingId: 'UA-7608407-2'
          profileId: '18929265'
